services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    networks:
      - app_network

  user:
    build:
      context: ./user
    ports:
      - "5002:5002"
    networks:
      - app_network

  item:
    build:
      context: ./item
    ports:
      - "5001:5001"
    networks:
      - app_network

  loadbalancer:
    image: nginx
    container_name: loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

networks:
  app_network:

