services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    networks:
      - app_network

  user:
    build:
      context: ./user
    ports:
      - "5002:5002"
    networks:
      - app_network

  item:
    build:
      context: ./item
    ports:
      - "5001:5001"
    networks:
      - app_network

networks:
  app_network:

